"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, BarChart3, BrainCircuit, Check, ChevronRight, CircleAlert, CircleDollarSign, Clipboard, Clock3, CreditCard, Database, FlaskConical, Globe2, LayoutDashboard, Lightbulb, LoaderCircle, Menu, Network, Play, Plug, Radar, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, Target, Video, Wallet, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { connectorCatalog, connectorCategories, type Connector } from "@/lib/connector-catalog";
import { DashboardOverview } from "./dashboard-overview";
import { MissionOutcome } from "./mission-outcome";
import { CampaignBriefPanel } from "./campaign-brief-panel";
import { TimelinePanel } from "./timeline-panel";
import { NotificationsPanel } from "./notifications-panel";
import { UsagePanel } from "./usage-panel";
import { ActionQueue as CanonicalActionQueue } from "./action-queue";
import { AgentRunsPanel } from "./agent-runs-panel";
import { ContactsPanel as CanonicalContactsPanel } from "./contacts-panel";
import { ContentPanel as CanonicalContentPanel } from "./content-panel";
import { EvidencePanel as CanonicalEvidencePanel } from "./evidence-panel";
import { ExperimentsPanel as CanonicalExperimentsPanel } from "./experiments-panel";
import { RevenuePanel as CanonicalRevenuePanel } from "./revenue-panel";
import { SettingsPanel } from "./settings-panel";
import { VersionsPanel as CanonicalVersionsPanel } from "./versions-panel";

type Mission = { mission_id:string; product_name:string; product_summary:string; executive_thesis:string; north_star_metric:string; icp:{segment:string;pain:string;trigger:string;exclusion:string}; strategy:{primary_channel:string;offer:string;message:string;why_now:string}; assumptions:{statement:string;confidence:number;evidence_needed:string}[]; agents:{name:string;role:string;output:string}[]; experiments:{title:string;hypothesis:string;action:string;metric:string;kill_rule:string}[]; content_queue:{platform:"YouTube"|"TikTok"|"X"|"Instagram"|"Website";format:string;hook:string;cta:string}[]; approval:{action:string;risk:string;reason:string} };
type MissionState = { mission_id:string;status:string;current_stage:string;cycle_number:number;payment_count:number;approved:boolean;created_at:number;updated_at:number };
type MissionEvent = { id:number;event_type:string;title:string;detail:string;actor:string;created_at:number };
type MissionPayload = { mission?:Mission|null;mode?:"simulation"|"live";inspected?:{final_url?:string};state?:MissionState;events?:MissionEvent[];error?:string };
type Connection = { id:string;provider:string;category:string;status:string;updated_at:number };
type WorkspaceSnapshot = { workspace:{id:string;display_name:string;owner_email:string;plan:string};connections:Connection[];mission_count:number };

async function loadInitialWorkspace(websiteUrl: string) {
  const workspaceResponse = await fetch("/api/workspace");
  const workspace = await workspaceResponse.json() as WorkspaceSnapshot & { error?: string };
  if (!workspaceResponse.ok) throw new Error(workspace.error || "Your workspace could not be opened.");
  let mission: MissionPayload;
  try {
    const response = await fetch("/api/mission", websiteUrl ? {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ website_url: websiteUrl }),
    } : undefined);
    mission = await response.json() as MissionPayload;
    if (!response.ok) mission = { error: mission.error || "Website analysis failed. Campaign planning is still available." };
  } catch {
    mission = { error: "Website analysis is unavailable. You can still use Campaign Brief." };
  }
  return { workspace, mission };
}
type View = "overview"|"brief"|"strategy"|"content"|"experiments"|"connectors"|"revenue"|"memory"|"actions"|"evidence"|"versions"|"budget"|"attribution"|"contacts"|"settings";

const seed:Mission={mission_id:"MISSION-PREVIEW",product_name:"Your product",product_summary:"Paste a public website to create its distribution mission.",executive_thesis:"One URL becomes a coordinated system of market intelligence, strategy, channel-native content, distribution experiments and revenue learning.",north_star_metric:"First attributable verified payment",icp:{segment:"Inferred after website analysis",pain:"Validated through response evidence",trigger:"Detected from intent signals",exclusion:"Low-urgency audiences"},strategy:{primary_channel:"Selected after analysis",offer:"Built from the website promise",message:"Generated from product evidence",why_now:"The fastest falsifiable route to payment is prioritized."},assumptions:[{statement:"The promise is clear enough to earn attention.",confidence:50,evidence_needed:"Target-customer reactions"},{statement:"A reachable first-customer segment exists.",confidence:50,evidence_needed:"Intent signals"},{statement:"The offer delivers value quickly.",confidence:50,evidence_needed:"Concierge test"}],agents:["Website Analyst","Market Scout","ICP Analyst","GTM Strategist","Content Director","Revenue Analyst"].map((name,index)=>({name,role:["Product intelligence","Demand research","Segmentation","Distribution","Content system","Learning loop"][index],output:"Waiting for mission context."})),experiments:[{title:"Promise test",hypothesis:"The promise earns qualified attention.",action:"Generated after analysis.",metric:"Qualified response",kill_rule:"Defined after baseline"},{title:"Distribution test",hypothesis:"One channel creates conversations.",action:"Generated after analysis.",metric:"Qualified conversations",kill_rule:"Defined after baseline"},{title:"Payment test",hypothesis:"A low-risk offer converts.",action:"Generated after analysis.",metric:"First payment",kill_rule:"Defined after baseline"}],content_queue:["Website","X","Instagram","TikTok","YouTube"].map(platform=>({platform:platform as Mission["content_queue"][number]["platform"],format:"Channel-native draft",hook:"Generated after analysis",cta:"Validate demand"})),approval:{action:"Approve the next external distribution batch",risk:"External communication can affect brand trust.",reason:"The system prepares autonomously; a human authorizes irreversible actions."}};

const loopStages=["observe","decide","approve","act","measure","learn"];
const navItems:[View,string,typeof LayoutDashboard][]=[["overview","Mission Control",LayoutDashboard],["brief","Campaign Brief",Target],["strategy","Intelligence",Lightbulb],["content","Content",Send],["experiments","Experiments",FlaskConical],["connectors","Connectors",Plug],["revenue","Revenue",CircleDollarSign],["memory","Agent Memory",Database],["actions","Action Queue",Clipboard],["evidence","Evidence",ShieldCheck],["versions","Versions",RefreshCw],["budget","Budget",Wallet],["attribution","Attribution",Network],["contacts","Audience",Activity],["settings","Settings",Settings2]];

export default function WorkspaceClient({userId,displayName,email,initialUrl}:{userId:string;displayName:string;email:string;initialUrl?:string}) {
  const [active,setActive]=useState<View>("overview"); const [url,setUrl]=useState(initialUrl||""); const [mission,setMission]=useState(seed); const [mode,setMode]=useState<"preview"|"simulation"|"live">("preview"); const [state,setState]=useState<MissionState|null>(null); const [events,setEvents]=useState<MissionEvent[]>([]); const [loading,setLoading]=useState(Boolean(initialUrl)); const [actionLoading,setActionLoading]=useState(false); const [error,setError]=useState(""); const [workspace,setWorkspace]=useState<WorkspaceSnapshot|null>(null); const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [selected,setSelected]=useState<Connector|null>(null); const [connectorLoading,setConnectorLoading]=useState(false); const [copied,setCopied]=useState(false);

  function hydrate(data:MissionPayload){if(!data.mission)return;setMission(data.mission);setMode(data.mode||"simulation");setState(data.state||null);setEvents(data.events||[]);if(data.inspected?.final_url)setUrl(data.inspected.final_url);}
  async function loadWorkspace(){const response=await fetch("/api/workspace");const data=await response.json() as WorkspaceSnapshot|null;if(response.ok)setWorkspace(data);}
  const initialRequest = useRef<{ url: string; promise: ReturnType<typeof loadInitialWorkspace> } | null>(null);
  useEffect(() => {
    const websiteUrl = initialUrl ?? "";
    // React's development effect replay must not create two missions.
    if (!initialRequest.current || initialRequest.current.url !== websiteUrl) {
      initialRequest.current = { url: websiteUrl, promise: loadInitialWorkspace(websiteUrl) };
    }
    let cancelled = false;
    initialRequest.current.promise.then(({ workspace, mission }) => {
      if (cancelled) return;
      setWorkspace(workspace);
      hydrate(mission);
      if (mission.error) setError(mission.error);
      if (!initialUrl && !mission.mission) setActive("brief");
      if (initialUrl) window.history.replaceState({}, "", "/workspace");
    }).catch(error => {
      if (!cancelled) setError(error instanceof Error ? error.message : "The workspace could not start the mission.");
    }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [initialUrl]);
  async function launchMission(event:React.FormEvent){event.preventDefault();setLoading(true);setError("");try{const response=await fetch("/api/mission",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({website_url:url})});const data=await response.json() as MissionPayload;if(!response.ok||!data.mission)throw new Error(data.error||"Website analysis failed.");hydrate(data);await loadWorkspace();setActive("overview");}catch(caught){setError(caught instanceof Error?caught.message:"Website analysis failed.")}finally{setLoading(false)}}
  async function runAction(action:"advance"|"approve"){if(!state)return;setActionLoading(true);setError("");try{const response=await fetch("/api/mission/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mission_id:state.mission_id,action})});const data=await response.json() as MissionPayload;if(!response.ok||!data.mission)throw new Error(data.error||"Agent action failed.");hydrate(data)}catch(caught){setError(caught instanceof Error?caught.message:"Agent action failed.")}finally{setActionLoading(false)}}
  async function prepareConnector(){if(!selected)return;setConnectorLoading(true);try{const response=await fetch("/api/connectors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:selected.name})});if(!response.ok)throw new Error("Connector setup failed.");await loadWorkspace();setSelected(null)}catch(caught){setError(caught instanceof Error?caught.message:"Connector setup failed.")}finally{setConnectorLoading(false)}}
  async function copyStrategy(){await navigator.clipboard.writeText(`${mission.product_name}\n${mission.executive_thesis}\n\nICP: ${mission.icp.segment}\nOffer: ${mission.strategy.offer}\nMessage: ${mission.strategy.message}`);setCopied(true);setTimeout(()=>setCopied(false),1500)}

  const filtered=useMemo(()=>connectorCatalog.filter(item=>(category==="All"||item.category===category)&&(`${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase()))),[query,category]);
  const prepared=new Set((workspace?.connections||[]).map(item=>item.provider));

  return <SidebarProvider className="workspace-shell"><Sidebar collapsible="offcanvas" className="workspace-sidebar"><SidebarHeader><Link href="/" className="workspace-brand"><span><Radar /></span><div><strong>Distribution OS</strong><small>Evidence-grounded mission system</small></div></Link></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{navItems.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={active===id} onClick={()=>setActive(id)} tooltip={label}><Icon/><span>{label}</span>{id==="connectors"&&<em>{workspace?.connections.length||0}</em>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter>{workspace?.workspace?.id&&<NotificationsPanel workspaceId={workspace.workspace.id} compact/>}<div className="workspace-user"><span>{displayName.slice(0,1).toUpperCase()}</span><div><strong>{displayName}</strong><small>{email}</small><small className="workspace-user-id">ID · {userId.slice(0,12)}</small></div></div></SidebarFooter></Sidebar><SidebarInset className="workspace-main"><header className="workspace-topbar"><div className="flex items-center gap-3"><SidebarTrigger><Menu/></SidebarTrigger><div><small>{mission.product_name}</small><strong>{navItems.find(item=>item[0]===active)?.[1]}</strong></div></div><div className="topbar-status"><span><i/>Mission {state?.current_stage||"not started"}</span><button onClick={()=>setActive("connectors")}><Plug/> {workspace?.connections.length||0} prepared</button></div></header>
    <div className="workspace-canvas">{error&&<div className="workspace-error"><CircleAlert/>{error}</div>}
      {active==="overview"&&<><Overview mission={mission} mode={mode} state={state} events={events} workspace={workspace} url={url} setUrl={setUrl} loading={loading} actionLoading={actionLoading} launchMission={launchMission} runAction={runAction} setActive={setActive}/><section className="overview-grid overview-dashboard-grid"><DashboardOverview workspaceId={workspace?.workspace?.id||""} /></section>{state?.mission_id&&<section className="overview-grid"><TimelinePanel missionId={state.mission_id} /></section>}</>}
      {active==="strategy"&&<StrategyPanel mission={mission} copyStrategy={copyStrategy} copied={copied}/>}
      <div hidden={active!=="brief"}>{workspace?.workspace?.id && <CampaignBriefPanel key={workspace.workspace.id}/>}</div>
      {active==="content"&&(state?.mission_id?<CanonicalContentPanel missionId={state.mission_id}/>:<MissionRequired view="content"/>)}
      {active==="experiments"&&(state?.mission_id?<CanonicalExperimentsPanel missionId={state.mission_id}/>:<MissionRequired view="experiments"/>)}
      {active==="connectors"&&<ConnectorsPanel query={query} setQuery={setQuery} category={category} setCategory={setCategory} prepared={prepared} filtered={filtered} setSelected={setSelected}/>}
      {active==="revenue"&&(state?.mission_id?<CanonicalRevenuePanel missionId={state.mission_id}/>:<MissionRequired view="revenue"/>)}
      {active==="memory"&&(state?.mission_id?<PageFrame eyebrow="Agent memory" title="Persisted runs and mission events" description={`${state.mission_id} · Cycle ${state.cycle_number} · ${state.current_stage}`}><AgentRunsPanel missionId={state.mission_id}/><TimelinePanel missionId={state.mission_id}/></PageFrame>:<MissionRequired view="agent memory"/>)}
      {active==="actions"&&(state?.mission_id?<CanonicalActionQueue missionId={state.mission_id}/>:<MissionRequired view="action queue"/>)}
      {active==="evidence"&&(state?.mission_id?<CanonicalEvidencePanel missionId={state.mission_id}/>:<MissionRequired view="evidence"/>)}
      {active==="versions"&&(state?.mission_id?<PageFrame eyebrow="Mission versions" title="Append-only strategy history" description={`${state.mission_id} · Cycle ${state.cycle_number}`}><CanonicalVersionsPanel missionId={state.mission_id}/></PageFrame>:<MissionRequired view="version history"/>)}
      {active==="budget"&&(workspace?.workspace?.id?<SettingsPanel workspaceId={workspace.workspace.id}/>:<MissionRequired view="budget settings"/>)}
      {active==="attribution"&&(state?.mission_id?<CanonicalRevenuePanel missionId={state.mission_id}/>:<MissionRequired view="attribution"/>)}
      {active==="contacts"&&(workspace?.workspace?.id?<CanonicalContactsPanel workspaceId={workspace.workspace.id}/>:<MissionRequired view="audience"/>)}
      {active==="settings"&&<PageFrame eyebrow="Workspace settings" title="Identity, plan and safety controls" description="Workspace-scoped configuration. Identity and audit signals are managed by the platform control plane."><section className="os-panel settings-page"><div className="settings-row"><small>Workspace</small><strong>{workspace?.workspace?.display_name||"Loading…"}</strong></div><div className="settings-row"><small>Owner</small><strong>{workspace?.workspace?.owner_email||email}</strong></div><div className="settings-row"><small>Plan</small><strong>{workspace?.workspace?.plan||"founder"}</strong></div><div className="settings-row"><small>Capabilities</small><strong>{workspace?.connections.length||0} prepared</strong></div></section>{workspace?.workspace?.id&&<><SettingsPanel workspaceId={workspace.workspace.id}/><UsagePanel workspaceId={workspace.workspace.id}/></>}</PageFrame>}
    </div>
    <Dialog open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="connector-dialog"><DialogHeader><DialogTitle>Prepare {selected?.name}</DialogTitle><DialogDescription>This creates a workspace-scoped connector record. The account is not connected until its OAuth or API authorization adapter is configured.</DialogDescription></DialogHeader><div className="permission-box"><ShieldCheck/><div><strong>Agent-safe authorization</strong><p>Credentials stay in the integration vault. Agents receive capabilities and scoped results—not raw secrets.</p></div></div><div className="permission-list"><span><Check/>Workspace-only ownership</span><span><Check/>Minimum required scopes</span><span><Check/>Revocable access</span><span><Check/>Audit trail for actions</span></div><DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}>Cancel</Button><Button onClick={prepareConnector} disabled={connectorLoading}>{connectorLoading?<LoaderCircle className="animate-spin"/>:<Plug/>}Prepare integration</Button></DialogFooter></DialogContent></Dialog>
  </SidebarInset></SidebarProvider>;
}

function Overview({mission,mode,state,events,workspace,url,setUrl,loading,actionLoading,launchMission,runAction,setActive}:{mission:Mission;mode:string;state:MissionState|null;events:MissionEvent[];workspace:WorkspaceSnapshot|null;url:string;setUrl:(value:string)=>void;loading:boolean;actionLoading:boolean;launchMission:(event:React.FormEvent)=>void;runAction:(action:"advance"|"approve")=>void;setActive:(view:View)=>void}) {
  const synthesisLabel=mode==="live"?"AI synthesized":mode==="simulation"?"Simulation":"Preview";
  return <>
    <section className="mission-command"><div><p className="section-label"><Sparkles/> Website-to-revenue mission</p><h1>{state?`Keep ${mission.product_name} moving toward its first customer.`:"Start with the only input Distribution OS needs."}</h1><p>{state?mission.executive_thesis:"Paste the public website. The system will create a persisted market thesis, strategy, content queue and learning plan."}</p></div><form onSubmit={launchMission}><Globe2/><Input type="url" required value={url} onChange={event=>setUrl(event.target.value)} aria-label="Website URL"/><Button disabled={loading}>{loading?<LoaderCircle className="animate-spin"/>:<Zap/>}{loading?"Building mission…":state?"Restart analysis":"Launch mission"}</Button></form></section>
    {state && <MissionOutcome key={state.mission_id} missionId={state.mission_id} refreshKey={state.updated_at} onNavigate={setActive} />}
    <section className="workspace-kpis"><article><span><Target/></span><div><small>North star</small><strong>{state?.payment_count||0} / 1 verified payment</strong></div><Progress value={state?.payment_count?100:0}/></article><article><span><RefreshCw/></span><div><small>Learning cycle</small><strong>{state?`Cycle ${state.cycle_number}`:"Not started"}</strong></div><em>{state?.current_stage||"observe"}</em></article><article><span><Network/></span><div><small>Capabilities</small><strong>{workspace?.connections.length||0} prepared</strong></div><button onClick={()=>setActive("connectors")}>Review setup <ArrowRight/></button></article><article><span><Activity/></span><div><small>Synthesis mode</small><strong>{synthesisLabel}</strong></div><em>{mode==="live"?"model response validated":"plan generation only"}</em></article></section>
    <div className="overview-grid"><section className="os-panel agent-loop-panel"><div className="panel-head"><div><p className="section-label"><BrainCircuit/> Mission lifecycle</p><h2>Governed stage transitions</h2></div><Button disabled={!state||actionLoading} onClick={()=>runAction("advance")}><Play/>{actionLoading?"Checking gates…":"Advance governed stage"}</Button></div><p>Stage changes are server-enforced. Approval and provider-confirmed execution are required before measurement.</p><div className="stage-rail">{loopStages.map((stage,index)=><div className={`stage-node ${state?.current_stage===stage?"stage-active":""}`} key={stage}><span>{index+1}</span><strong>{stage}</strong><small>{stage==="approve"?"human gate":"governed"}</small></div>)}</div><div className="agent-mini-grid">{mission.agents.map((agent,index)=><article key={agent.name}><span>{index+1}</span><div><strong>{agent.name}</strong><small>{agent.role}</small></div><em>{mode==="preview"?"not run":mode==="simulation"?"simulated":"recorded"}</em></article>)}</div></section><section className="os-panel priority-panel"><div className="panel-head"><div><p className="section-label"><Target/> Proposed experiment</p><h2>{mission.experiments[0].title}</h2></div><span className="priority-score">P1</span></div><p>{mission.experiments[0].action}</p><div><small>Success signal</small><strong>{mission.experiments[0].metric}</strong></div><div><small>Kill rule</small><strong>{mission.experiments[0].kill_rule}</strong></div><button onClick={()=>setActive("experiments")}>Open persisted experiments <ChevronRight/></button></section></div>
    <div className="overview-grid lower"><section className="os-panel"><div className="panel-head"><div><p className="section-label"><Clock3/> Mission events</p><h2>Latest persisted events</h2></div><button onClick={()=>setActive("memory")}>Full memory</button></div><EventList events={events.slice(0,4)}/></section><section className={`approval-card ${state?.approved?"approved":""}`}><ShieldCheck/><div><small>Human control boundary</small><h2>{state?.approved?"An exact action was approved":"Review the exact queued action"}</h2><p>{mission.approval.reason}</p></div><Button disabled={!state} onClick={()=>setActive("actions")}>{state?.approved?<><Check/>Open approval record</>:"Open action queue"}</Button></section></div>
  </>;
}

function PageFrame({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:React.ReactNode}){return <section className="page-frame"><header><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></header>{children}</section>}
function MissionRequired({view}:{view:string}){return <PageFrame eyebrow="Canonical workspace data" title={`Launch a mission to open ${view}`} description="This view shows persisted tenant-owned records only. Preview data is never presented as live operational state."><section className="os-panel"><p className="empty-ledger">Paste a public website URL in Mission Control to create the first mission.</p></section></PageFrame>}
function Insight({label,value}:{label:string;value:string}){return <div className="strategy-insight"><small>{label}</small><p>{value}</p></div>}
function EventList({events}:{events:MissionEvent[]}){return <div className="event-list workspace-events">{events.length?events.map(event=><article key={event.id}><span className={`event-dot event-${event.event_type}`}/><div><strong>{event.title}</strong><p>{event.detail}</p><small>{event.actor} · {new Date(event.created_at).toLocaleString()}</small></div></article>):<p className="empty-ledger">No evidence yet. Launch the website mission to begin.</p>}</div>}
function ConnectorMark({name}:{name:string}){const Icon=name==="Stripe"?CreditCard:name==="YouTube"?Video:name==="Metricool"?BarChart3:name==="X"?Zap:name==="Gmail"?Send:name==="Reddit"?Activity:name==="TikTok"?Activity:name==="Instagram"?Activity:Plug;return <span className="connector-mark"><Icon/></span>}

function StrategyPanel({mission,copyStrategy,copied}:{mission:Mission;copyStrategy:()=>void;copied:boolean}){return <PageFrame eyebrow="Market intelligence" title="A focused path to the first customer" description={mission.product_summary}><div className="strategy-layout"><section className="os-panel strategy-stack"><Insight label="Ideal customer" value={mission.icp.segment}/><Insight label="Pain" value={mission.icp.pain}/><Insight label="Urgent trigger" value={mission.icp.trigger}/><Insight label="Exclude" value={mission.icp.exclusion}/></section><section className="os-panel strategy-core"><p className="section-label"><Target/> Strategic thesis</p><h2>{mission.strategy.message}</h2><Insight label="Primary channel" value={mission.strategy.primary_channel}/><Insight label="Founder offer" value={mission.strategy.offer}/><Insight label="Why now" value={mission.strategy.why_now}/><Button onClick={copyStrategy}>{copied?<Check/>:<Clipboard/>}{copied?"Copied":"Copy GTM brief"}</Button></section></div><div className="assumption-grid">{mission.assumptions.map(item=><article key={item.statement}><div><span>Confidence</span><strong>{item.confidence}%</strong></div><Progress value={item.confidence}/><h3>{item.statement}</h3><p>Evidence needed · {item.evidence_needed}</p></article>)}</div></PageFrame>}

function ConnectorsPanel({query,setQuery,category,setCategory,prepared,filtered,setSelected}:{query:string;setQuery:(value:string)=>void;category:string;setCategory:(value:string)=>void;prepared:Set<string>;filtered:Connector[];setSelected:(connector:Connector|null)=>void}){return <PageFrame eyebrow="Connector hub" title={`${connectorCatalog.length} providers catalogued. Two verified runtime boundaries.`} description="Resend can execute one governed sandbox email and Stripe can ingest signed payment events. Every other provider is roadmap-only until a real adapter and health check are verified."><div className="connector-toolbar"><div><Search/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search Resend, Stripe, Gmail, YouTube…"/></div><span>{prepared.size} setup records · {filtered.length} shown</span></div><div className="category-pills">{connectorCategories.map(item=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><div className="connector-grid">{filtered.map(item=><article key={item.name}><ConnectorMark name={item.name}/><div><h3>{item.name}</h3><p>{item.description}</p><small>{item.category} · {item.availability==="live_execution"?"Executable sandbox":item.availability==="verified_ingestion"?"Verified webhook intake":"Roadmap only"}</small></div>{prepared.has(item.name)?<button className="connector-ready" disabled><Settings2/>Setup record only</button>:item.availability==="roadmap"?<button disabled>Roadmap only</button>:<button onClick={()=>setSelected(item)}>{item.availability==="live_execution"?"Prepare sandbox":"Review intake"} <ArrowRight/></button>}</article>)}</div></PageFrame>}
